In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('./input/controlesVinardo.csv')
df

                  Ligand Receptor  Affinity1  Affinity2  Affinity3
0              CadeiaC14   lcUSP1   -7.55187   -7.23380   -7.06628
1              CadeiaC14   lcUSP2   -7.57209   -6.99969   -6.99321
2              CadeiaC14   lcUSP3   -7.15325   -7.14594   -7.12207
3              CadeiaC16   lcUSP1   -7.63592   -7.55026   -7.46221
4              CadeiaC16   lcUSP2   -7.50902   -7.38964   -6.95884
...                  ...      ...        ...        ...        ...
2125  fattyacidsDecoy998   lcUSP2  -10.08290   -9.95714   -9.45434
2126  fattyacidsDecoy998   lcUSP3  -11.50488  -10.47942  -10.45567
2127  fattyacidsDecoy999   lcUSP1  -10.94376   -9.86000   -9.31851
2128  fattyacidsDecoy999   lcUSP2   -9.61842   -9.46012   -9.40341
2129  fattyacidsDecoy999   lcUSP3  -10.17850   -9.94024   -9.81073

[2130 rows x 5 columns]

### Calculating the Mean of the Highest score value for all model

In [8]:
newdf = df.drop(df.columns[[3,4,]], axis=1)
newdf

                  Ligand Receptor  Affinity1
0              CadeiaC14   lcUSP1   -7.55187
1              CadeiaC14   lcUSP2   -7.57209
2              CadeiaC14   lcUSP3   -7.15325
3              CadeiaC16   lcUSP1   -7.63592
4              CadeiaC16   lcUSP2   -7.50902
...                  ...      ...        ...
2125  fattyacidsDecoy998   lcUSP2  -10.08290
2126  fattyacidsDecoy998   lcUSP3  -11.50488
2127  fattyacidsDecoy999   lcUSP1  -10.94376
2128  fattyacidsDecoy999   lcUSP2   -9.61842
2129  fattyacidsDecoy999   lcUSP3  -10.17850

[2130 rows x 3 columns]

In [9]:
ndf = newdf.groupby(['Ligand']).mean()
ndf

                    Affinity1
Ligand
CadeiaC14           -7.425737
CadeiaC16           -7.577237
CadeiaC18           -8.251323
EPH                -10.647637
EPHcadeia1          -7.767050
...                       ...
fattyacidsDecoy986  -8.969267
fattyacidsDecoy987 -10.716003
fattyacidsDecoy99  -11.725153
fattyacidsDecoy998 -10.677847
fattyacidsDecoy999 -10.246893

[711 rows x 1 columns]

In [11]:
ndf.to_csv("./output/controleVinardoUmaPoseMedia.csv")

In [ ]:
### Calculating the Mean of the THREE Highest score value for all model

In [40]:
ndf = df.groupby(['Ligand']).mean()
ndf

                Affinity1  Affinity2  Affinity3
Ligand
BPB10           -7.604907  -7.421393  -7.180047
BPB8            -7.327487  -7.164393  -7.116363
BPB9            -7.491670  -7.160953  -7.036870
diamideDecoy1   -5.567890  -5.434953  -5.413470
diamideDecoy10  -5.082900  -4.892863  -4.628297
...                   ...        ...        ...
meta-diamide5   -8.055077  -7.611337  -7.385723
meta-diamide6   -7.680940  -7.397730  -7.119163
meta-diamide7   -7.869713  -7.636830  -7.486103
meta-diamide8   -7.446423  -7.253017  -7.053450
meta-diamide9   -7.764060  -7.559603  -7.476733

[426 rows x 3 columns]

In [41]:
Ndf = ndf.mean(axis=1)
Ndf

Ligand
BPB10            -7.402116
BPB8             -7.202748
BPB9             -7.229831
diamideDecoy1    -5.472104
diamideDecoy10   -4.868020
                    ...
meta-diamide5    -7.684046
meta-diamide6    -7.399278
meta-diamide7    -7.664216
meta-diamide8    -7.250963
meta-diamide9    -7.600132
Length: 426, dtype: float64

In [42]:
Ndf.to_csv("controleVinardo3Media.csv")

In [90]:
df

                                 Affinity1  Affinity2  Affinity3
Ligand
2iodo-2tetrahydroacridin         -8.606500  -8.545285  -8.159202
2iodo-2tetrahydroacridindecoy10  -7.521603  -7.042447  -6.652437
2iodo-2tetrahydroacridindecoy11  -8.381435  -7.475077  -6.837680
2iodo-2tetrahydroacridindecoy12  -9.834907  -9.550068  -8.858992
2iodo-2tetrahydroacridindecoy13 -10.152812  -9.777382  -9.045557
...                                    ...        ...        ...
Velnacrinedecoy50                -6.610000  -6.442830  -6.307087
Velnacrinedecoy6                 -6.721310  -6.504725  -6.339753
Velnacrinedecoy7                 -6.555240  -6.100648  -6.026703
Velnacrinedecoy8                 -6.365983  -6.217980  -6.067995
Velnacrinedecoy9                 -6.639703  -6.419885  -6.308850

[781 rows x 3 columns]

In [91]:
col = df.loc[: , "Affinity1":"Affinity3"]

In [92]:
df['Affinity_mean'] = col.mean(axis=1)
df

,Affinity1,Affinity2,Affinity3,Affinity_mean
Ligand,,,,
2iodo-2tetrahydroacridin,-8.606500,-8.545285,-8.159202,-8.436996
2iodo-2tetrahydroacridindecoy10,-7.521603,-7.042447,-6.652437,-7.072163
2iodo-2tetrahydroacridindecoy11,-8.381435,-7.475077,-6.837680,-7.564731
2iodo-2tetrahydroacridindecoy12,-9.834907,-9.550068,-8.858992,-9.414656
2iodo-2tetrahydroacridindecoy13,-10.152812,-9.777382,-9.045557,-9.658584
...,...,...,...,...
Velnacrinedecoy50,-6.610000,-6.442830,-6.307087,-6.453306
Velnacrinedecoy6,-6.721310,-6.504725,-6.339753,-6.521929
Velnacrinedecoy7,-6.555240,-6.100648,-6.026703,-6.227530
Velnacrinedecoy8,-6.365983,-6.217980,-6.067995,-6.217319
Velnacrinedecoy9,-6.639703,-6.419885,-6.308850,-6.456146

In [93]:
df.to_csv("controleDkoesMedia.csv")